name: AIAGroup_CodingAssesment
description: Open source code library.

version: 1.0+1

environment:
  sdk: ">=1.12.8 <3.0.0"
  # sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cached_network_image: ^1.1.3
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/images/img_logo_aiadefault.png
  - assets/images/img_logo_aiared.png
  - assets/images/img_logo_aiawhite.png
  
  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
  
flutter_launcher_icons:
  path: assets/images/img_logo_aiadefault.png
      
flutter_icons:
  image_path_android: assets/images/img_logo_aiadefault.png
  image_path_ios: assets/images/img_logo_aiadefault.png
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true